language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  ##Tagging
  - docker tag reverseproxy duydd3/reverseproxy
  - docker tag udagram-api-feed duydd3/udagram-api-feed
  - docker tag udagram-api-user duydd3/udagram-api-user
  - docker tag udagram-frontend duydd3/udagram-frontend:local
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push duydd3/reverseproxy
  - docker push duydd3/udagram-api-feed
  - docker push duydd3/udagram-api-user
  - docker push duydd3/udagram-frontend:local